services:
  cli:
    restart: unless-stopped
    #image: odk-mailer:rc1
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - odk_mailer_data:/root/.odk-mailer
      - odk_mailer_projects:/root/projects
      - type: bind
        source: ./test-data
        target: /root/test-data
    environment:
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS=${SMTP_PASS}
        - ODK_HOST=${ODK_HOST}
        - CRON_FREQUENCY=${CRON_FREQUENCY}
        - NOTIFY_TO=${NOTIFY_TO}
        - NOTIFY_FROM=${NOTIFY_FROM}

volumes:
  odk_mailer_data:
  odk_mailer_projects: