services:
  cli:
    #image: odk-mailer:rc1
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - odk_mailer_data:/root/.odk-mailer
      - type: bind
        source: test-data
        target: /root/test-data

volumes:
  odk_mailer_data: