services:
  cli:
    #image: odk-mailer:rc1
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - odk_mailer_data:/root/.odk-mailer
      - type: bind
        source: test-data
        target: /root/test-data
    environment:
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS=${SMTP_PASS}
        - ODK_HOST=${ODK_HOST}

volumes:
  odk_mailer_data: